export const models = [
  // {
  //   id: 0,
  //   title: "Planet",
  //   camera: { x: 15, y: 5, z: 10 },
  //   target: { x: 0, y: 0, z: 0 },
  // },
  // {
  //   id: 1,
  //   title: "Computer",
  //   camera: { x: 0, y: 5, z: 10 },
  //   target: { x: 90, y: 0, z: 90 },
  // },
  // {
  //   id: 2,
  //   title: "Example",
  //   camera: { x: 0, y: 5, z: 10 },
  //   target: { x: -90, y: 0, z: 90 },
  // },
  // {
  //   id: 3,
  //   title: "Example",
  //   camera: { x: 0, y: 5, z: 10 },
  //   target: { x: 90, y: 0, z: -90 },
  // },
  // {
  //   id: 4,
  //   title: "Example",
  //   camera: { x: 0, y: 5, z: 10 },
  //   target: { x:- 90, y: 0, z: -90 },
  // },
  {
    id: 0,
    title: "Planet",
    description: "  Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quos qui odio quibusdam deserunt magni, maiores ipsum quo sunt unde omnis.",
    camera: { x: 15, y: 5, z: 10 },
    target: { x: 0, y: 0, z: 0 },
  },
  {
    id: 1,
    title: "Computer",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit praesentium autem, veritatis provident laborum corrupti quas pariatur. Suscipit, vel accusantium!",
    camera: { x: 0, y: 5, z: 10 },
    target: { x: 20, y: 0, z:0},
  },
  {
    id: 2,
    title: "Example",
    description: "  Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis dolorum debitis optio numquam eius atque ratione sunt illo incidunt inventore?",
    camera: { x: 0, y: 5, z: 10 },
    target: { x: 0, y: 0, z: 0},
  },
  {
    id: 3,
    title: "Example",
    description: "  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error odio et est eligendi enim, distinctio adipisci quos cumque voluptatum aliquam!",
    camera: { x: 0, y: 5, z: 10 },
    target: { x: 0, y: 0, z: 0},
  },
  {
    id: 4,
    title: "Example",
    description: "  Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur sint nemo amet iste eos voluptatibus doloribus, nobis eveniet modi velit.",
    camera: { x: 0, y: 5, z: 10 },
    target: { x:-0, y: 0, z: 0 },
  },
];
